# Generated by Django 3.1.5 on 2021-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sytoapp', '0004_auto_20210128_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='siema', max_length=10),
        ),
    ]
