# Generated by Django 3.1.5 on 2021-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sytoapp', '0007_remove_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
