# Generated by Django 3.1.5 on 2021-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sytoapp', '0014_homeworkersevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkersevent',
            name='day_quantity',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homeworkersevent',
            name='people_quantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
