# Generated by Django 3.1.5 on 2021-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sytoapp', '0015_auto_20210212_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkersevent',
            name='day_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homeworkersevent',
            name='people_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
